const allowedAttributes: Record<string, Set<string>> = {
  a: new Set(['href', 'name', 'target']),
  img: new Set(['src', 'srcset', 'alt', 'title', 'width', 'height', 'loading']),
}

const allowedSchemes = new Set(['http', 'https', 'ftp', 'mailto', 'tel'])
const allowedSchemesAppliedToAttributes = new Set(['href', 'src', 'cite'])

type DisallowedTagsMode = 'discard' | 'escape' | 'block'
const disallowedTagsMode: DisallowedTagsMode = 'discard'

const allowedTags = new Set([
  // Content sectioning tags
  'address',
  'article',
  'aside',
  'footer',
  'header',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hgroup',
  'main',
  'nav',
  'section',
  // Text content
  'blockquote',
  'dd',
  'div',
  'dl',
  'dt',
  'figcaption',
  'figure',
  'hr',
  'li',
  'main',
  'ol',
  'p',
  'pre',
  'ul',
  // Inline text semantics tags
  'a',
  'abbr',
  'b',
  'bdi',
  'bdo',
  'br',
  'cite',
  'code',
  'data',
  'dfn',
  'em',
  'i',
  'kbd',
  'mark',
  'q',
  'rb',
  'rp',
  'rt',
  'rtc',
  'ruby',
  's',
  'samp',
  'small',
  'span',
  'strong',
  'sub',
  'sup',
  'time',
  'u',
  'var',
  'wbr',
  // Table tags
  'caption',
  'col',
  'colgroup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'tr',
  // Media tags
  'img',
])
